#
# Parsed SAI objects and parsers:
#
# The SAI objects are parsed from the P4Runtime JSON file, generated by p4 compiler, which contains the information
# of all tables and entry information.
# 
# The classes below are used to parse the P4Runtime JSON file to get the key information, so we can generate the SAI
# API headers and implementation files afterwards.
#
# At high level, the hiredarchy of the SAI objects is as follows:
#
# DASHSAIExtensions                     : All DASH SAI extensions.
# |- SAIEnum                            : A single enum type.
# |  |- SAIEnumMember                   : A single enum member within the enum.
# |- SAIAPISet                          : All information for a single SAI API set, such as routing or CA-PA mapping.
#    |- SAIAPITable                 : All information for a single SAI API table used in the API set.
#       |- SAIAPITableKey               : Information of a single P4 table key defined in the table.
#       |- SAIAPITableAction  <-------| : Information of a single P4 table action defined used by the table.
#          |- SAIAPITableActionParam -| : Information of a single P4 table action parameter used by the action.
#
from .dash_sai_extensions import DashP4SAIExtensions
from .dash_p4_table_group import DashP4TableGroup
from .dash_p4_table import DashP4Table
from .dash_p4_table_action import DashP4TableAction
from .dash_p4_table_key import DashP4TableKey
from .dash_p4_table_action_param import DashP4TableActionParam
from .dash_p4_counter import DashP4Counter
from .dash_p4_enum import DashP4Enum
from .dash_p4_enum_member import DashP4EnumMember