
API_NAME       = "api_name"
SAI_KEY_NAME   = "sai_key_name"
DEFAULT_ONLY   = "default_only"
SAI            = "sai"
ISOBJECT       = "isobject"
TYPE           = "type"
ISRESOURCETYPE = "isresourcetype"
OBJECTS        = "objects"
ISREADONLY     = "isreadonly"
SKIPATTR       = "skipattr"