dashone: test.cpp
	g++ \
	    -I SAI/inc \
	    -I SAI/experimental/ \
	    -o test test.cpp saidash.cpp \
	    -L/usr/local/lib/ \
	    -lpthread \
	    -lpiprotogrpc \
	    -lpiprotobuf \
	    -lprotobuf \
	    -lgrpc++ \
	    -lgrpc \
	    -lpiall \
	    -lpi_dummy \
	    -lpthread \
	    -labsl_synchronization \
	    -g


